apiVersion: v1
kind: PersistentVolume
metadata:
  name: urlshorten-pv
  labels:
    pv: urlshorten-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/worker2/bookmyshow/urlshorten

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: urlshorten-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      pv: urlshorten-pv

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshorten-deploy
spec:
  selector:
    matchLabels:
      app: urlshorten-deploy
  template:
    metadata:
      labels:
        app: urlshorten-deploy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: name
                  operator: In
                  values:
                    - worker2
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "red"
          effect: "NoSchedule"
      containers:
        - name: web
          image: shubhamdevops2/urlshorten:15
          imagePullPolicy: Always
          resources:
            limits:
              memory: "450Mi"
              cpu: "400m"
            requests:
              memory: "350Mi"
              cpu: "300m"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: urlshorten-volume
              mountPath: /app
      volumes:
        - name: urlshorten-volume
          persistentVolumeClaim:
            claimName: urlshorten-pvc


---

apiVersion: v1
kind: Service
metadata:
  name: urlshorten-svc
spec:
  selector:
    app: urlshorten-deploy
  ports:
  - name: web
    port: 3000
    targetPort: 3000


---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: "urlshorten-hpa"
  namespace: default
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: urlshorten-deploy
  targetCPUUtilizationPercentage: 70
